"""update_ako_tables

Revision ID: 3d5c12cb467f
Revises: fix_column_mismatch
Create Date: 2025-04-30 01:34:40.933735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3d5c12cb467f'
down_revision: Union[str, None] = 'fix_column_mismatch'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.campus_id'], ),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_courses_course_id'), 'courses', ['course_id'], unique=False)
    op.create_table('strands',
    sa.Column('strand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.campus_id'], ),
    sa.PrimaryKeyConstraint('strand_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_strands_strand_id'), 'strands', ['strand_id'], unique=False)
    op.drop_constraint('campuses_ibfk_1', 'campuses', type_='foreignkey')
    op.drop_column('campuses', 'user_id')
    op.drop_index('ix_previous_schools_id', table_name='previous_schools')
    op.create_index(op.f('ix_previous_schools_previousSchool_id'), 'previous_schools', ['previousSchool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_previous_schools_previousSchool_id'), table_name='previous_schools')
    op.create_index('ix_previous_schools_id', 'previous_schools', ['previousSchool_id'], unique=False)
    op.add_column('campuses', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('campuses_ibfk_1', 'campuses', 'users', ['user_id'], ['user_id'])
    op.drop_index(op.f('ix_strands_strand_id'), table_name='strands')
    op.drop_table('strands')
    op.drop_index(op.f('ix_courses_course_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
