"""added previous_schoo.id to college_students table

Revision ID: 3eb5cb318ee2
Revises: 9459b773c874
Create Date: 2025-04-13 20:17:28.515605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb5cb318ee2'
down_revision: Union[str, None] = '9459b773c874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
