"""event report migrations

Revision ID: 4646f8dc0421
Revises: 9bb790644de8
Create Date: 2025-03-18 23:41:24.043583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4646f8dc0421'
down_revision: Union[str, None] = '9bb790644de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_reports',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('total_area', sa.Float(), nullable=False),
    sa.Column('number_of_students_affected', sa.Integer(), nullable=False),
    sa.Column('geojson_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_event_reports_event_id'), 'event_reports', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_reports_event_id'), table_name='event_reports')
    op.drop_table('event_reports')
    # ### end Alembic commands ###
