"""update event report migrations

Revision ID: 4925de4216dd
Revises: 657a02e35514
Create Date: 2025-03-19 13:04:32.383143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4925de4216dd'
down_revision: Union[str, None] = '657a02e35514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_reports', sa.Column('clustering_type', sa.String(length=100), nullable=True))
    op.add_column('event_reports', sa.Column('education_level', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_reports', 'education_level')
    op.drop_column('event_reports', 'clustering_type')
    # ### end Alembic commands ###
