"""new model previous school migrations

Revision ID: 5dcdc2dce5c7
Revises: 92353f1aa4f8
Create Date: 2025-04-11 00:03:05.952183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5dcdc2dce5c7'
down_revision: Union[str, None] = '92353f1aa4f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('previous_schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_previous_schools_id'), 'previous_schools', ['id'], unique=False)
    op.create_index(op.f('ix_previous_schools_name'), 'previous_schools', ['name'], unique=False)
    op.add_column('senior_high_students', sa.Column('previous_school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'senior_high_students', 'previous_schools', ['previous_school_id'], ['id'])
    op.drop_column('senior_high_students', 'previous_school')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('senior_high_students', sa.Column('previous_school', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'senior_high_students', type_='foreignkey')
    op.drop_column('senior_high_students', 'previous_school_id')
    op.drop_index(op.f('ix_previous_schools_name'), table_name='previous_schools')
    op.drop_index(op.f('ix_previous_schools_id'), table_name='previous_schools')
    op.drop_table('previous_schools')
    # ### end Alembic commands ###
