"""update migrations

Revision ID: 6106312fc606
Revises: 7203d096003a
Create Date: 2025-04-14 15:15:01.540415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6106312fc606'
down_revision: Union[str, None] = '7203d096003a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('college_students', sa.Column('cluster', sa.Integer(), nullable=True))
    op.drop_column('college_students', 'cluster_proximity')
    op.drop_column('college_students', 'cluster_address')
    op.add_column('senior_high_students', sa.Column('cluster', sa.Integer(), nullable=True))
    op.drop_column('senior_high_students', 'cluster_proximity')
    op.drop_column('senior_high_students', 'cluster_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('senior_high_students', sa.Column('cluster_address', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('senior_high_students', sa.Column('cluster_proximity', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('senior_high_students', 'cluster')
    op.add_column('college_students', sa.Column('cluster_address', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('college_students', sa.Column('cluster_proximity', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('college_students', 'cluster')
    # ### end Alembic commands ###
