"""add relationship to strands and courses

Revision ID: 6c2411f72891
Revises: 3d5c12cb467f
Create Date: 2025-04-30 01:57:44.571835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c2411f72891'
down_revision: Union[str, None] = '3d5c12cb467f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('college_students', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'college_students', 'courses', ['course_id'], ['course_id'])
    op.add_column('senior_high_students', sa.Column('strand_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'senior_high_students', 'strands', ['strand_id'], ['strand_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'senior_high_students', type_='foreignkey')
    op.drop_column('senior_high_students', 'strand_id')
    op.drop_constraint(None, 'college_students', type_='foreignkey')
    op.drop_column('college_students', 'course_id')
    # ### end Alembic commands ###
