"""add relationship between users and campuses

Revision ID: 7dc8b59c16fd
Revises: 1831be895b4d
Create Date: 2025-04-17 18:15:08.407469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7dc8b59c16fd'
down_revision: Union[str, None] = '1831be895b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campuses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'campuses', 'users', ['user_id'], ['user_id'])
    op.add_column('college_students', sa.Column('cluster', sa.Integer(), nullable=True))
    op.drop_column('college_students', 'cluster_proximity')
    op.drop_column('college_students', 'updated_at')
    op.drop_column('college_students', 'cluster_address')
    op.drop_column('college_students', 'uploaded_at')
    op.add_column('senior_high_students', sa.Column('cluster', sa.Integer(), nullable=True))
    op.drop_column('senior_high_students', 'cluster_proximity')
    op.drop_column('senior_high_students', 'uploaded_at')
    op.drop_column('senior_high_students', 'cluster_address')
    op.drop_column('senior_high_students', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('senior_high_students', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('senior_high_students', sa.Column('cluster_address', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('senior_high_students', sa.Column('uploaded_at', mysql.DATETIME(), nullable=True))
    op.add_column('senior_high_students', sa.Column('cluster_proximity', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('senior_high_students', 'cluster')
    op.add_column('college_students', sa.Column('uploaded_at', mysql.DATETIME(), nullable=True))
    op.add_column('college_students', sa.Column('cluster_address', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('college_students', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('college_students', sa.Column('cluster_proximity', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('college_students', 'cluster')
    op.drop_constraint(None, 'campuses', type_='foreignkey')
    op.drop_column('campuses', 'user_id')
    # ### end Alembic commands ###
