"""revised conflicted naming for shs and college tables

Revision ID: 850b471d28ab
Revises: e870875d730a
Create Date: 2025-04-13 22:16:25.628683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '850b471d28ab'
down_revision: Union[str, None] = 'e870875d730a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
