"""update migrations

Revision ID: 9459b773c874
Revises: 546caa829f46
Create Date: 2025-04-13 20:16:11.809521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9459b773c874'
down_revision: Union[str, None] = '546caa829f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('college_students', sa.Column('previous_school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'college_students', 'previous_schools', ['previous_school_id'], ['id'])
    op.drop_column('college_students', 'previous_school')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('college_students', sa.Column('previous_school', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'college_students', type_='foreignkey')
    op.drop_column('college_students', 'previous_school_id')
    # ### end Alembic commands ###
