"""new model migrations

Revision ID: a43d23307c75
Revises: 62a4b280c54f
Create Date: 2025-04-29 23:08:28.756998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a43d23307c75'
down_revision: Union[str, None] = '62a4b280c54f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.campus_id'], ),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_courses_course_id'), 'courses', ['course_id'], unique=False)
    op.create_table('strands',
    sa.Column('strand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.campus_id'], ),
    sa.PrimaryKeyConstraint('strand_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_strands_strand_id'), 'strands', ['strand_id'], unique=False)
    op.drop_constraint('college_students_ibfk_1', 'college_students', type_='foreignkey')
    op.create_foreign_key(None, 'college_students', 'previous_schools', ['previous_school_id'], ['previousSchool_id'])
    op.add_column('previous_schools', sa.Column('previousSchool_id', sa.Integer(), nullable=False))
    op.drop_index('ix_previous_schools_id', table_name='previous_schools')
    op.create_index(op.f('ix_previous_schools_previousSchool_id'), 'previous_schools', ['previousSchool_id'], unique=False)
    op.drop_column('previous_schools', 'id')
    op.drop_constraint('senior_high_students_ibfk_1', 'senior_high_students', type_='foreignkey')
    op.create_foreign_key(None, 'senior_high_students', 'previous_schools', ['previous_school_id'], ['previousSchool_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'senior_high_students', type_='foreignkey')
    op.create_foreign_key('senior_high_students_ibfk_1', 'senior_high_students', 'previous_schools', ['previous_school_id'], ['id'])
    op.add_column('previous_schools', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_previous_schools_previousSchool_id'), table_name='previous_schools')
    op.create_index('ix_previous_schools_id', 'previous_schools', ['id'], unique=False)
    op.drop_column('previous_schools', 'previousSchool_id')
    op.drop_constraint(None, 'college_students', type_='foreignkey')
    op.create_foreign_key('college_students_ibfk_1', 'college_students', 'previous_schools', ['previous_school_id'], ['id'])
    op.drop_index(op.f('ix_strands_strand_id'), table_name='strands')
    op.drop_table('strands')
    op.drop_index(op.f('ix_courses_course_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
