"""update user model migrations

Revision ID: b43ae7d95942
Revises: cffd4f88062c
Create Date: 2025-03-11 19:10:34.334192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43ae7d95942'
down_revision: Union[str, None] = 'cffd4f88062c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college_students',
    sa.Column('stud_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('course', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('strand', sa.String(length=50), nullable=True),
    sa.Column('previous_school', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=255), nullable=True),
    sa.Column('barangay', sa.String(length=255), nullable=True),
    sa.Column('full_address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('cluster_address', sa.Integer(), nullable=True),
    sa.Column('cluster_proximity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('stud_id')
    )
    op.create_index(op.f('ix_college_students_stud_id'), 'college_students', ['stud_id'], unique=False)
    op.create_table('senior_high_students',
    sa.Column('stud_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('strand', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('previous_school', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('barangay', sa.String(length=255), nullable=True),
    sa.Column('full_address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('cluster_address', sa.Integer(), nullable=True),
    sa.Column('cluster_proximity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('stud_id')
    )
    op.create_index(op.f('ix_senior_high_students_stud_id'), 'senior_high_students', ['stud_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_senior_high_students_stud_id'), table_name='senior_high_students')
    op.drop_table('senior_high_students')
    op.drop_index(op.f('ix_college_students_stud_id'), table_name='college_students')
    op.drop_table('college_students')
    # ### end Alembic commands ###
