"""campus model migrations

Revision ID: b8221b13f4bb
Revises: 5dcdc2dce5c7
Create Date: 2025-04-11 19:56:23.928740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8221b13f4bb'
down_revision: Union[str, None] = '5dcdc2dce5c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campuses',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('campus_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_campuses_campus_id'), 'campuses', ['campus_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campuses_campus_id'), table_name='campuses')
    op.drop_table('campuses')
    # ### end Alembic commands ###
