"""added tracking upload data for college and shs tables

Revision ID: bc12cf77f49f
Revises: 3eb5cb318ee2
Create Date: 2025-04-13 22:06:24.198189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc12cf77f49f'
down_revision: Union[str, None] = '3eb5cb318ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('college_students', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('college_students', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('college_students', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('college_students', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'college_students', 'users', ['created_by'], ['user_id'])
    op.create_foreign_key(None, 'college_students', 'users', ['updated_by'], ['user_id'])
    op.add_column('senior_high_students', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('senior_high_students', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('senior_high_students', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('senior_high_students', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'senior_high_students', 'users', ['created_by'], ['user_id'])
    op.create_foreign_key(None, 'senior_high_students', 'users', ['updated_by'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'senior_high_students', type_='foreignkey')
    op.drop_constraint(None, 'senior_high_students', type_='foreignkey')
    op.drop_column('senior_high_students', 'updated_at')
    op.drop_column('senior_high_students', 'created_at')
    op.drop_column('senior_high_students', 'updated_by')
    op.drop_column('senior_high_students', 'created_by')
    op.drop_constraint(None, 'college_students', type_='foreignkey')
    op.drop_constraint(None, 'college_students', type_='foreignkey')
    op.drop_column('college_students', 'updated_at')
    op.drop_column('college_students', 'created_at')
    op.drop_column('college_students', 'updated_by')
    op.drop_column('college_students', 'created_by')
    # ### end Alembic commands ###
