"""updated relationship conflict for prev school tables to respective tables

Revision ID: e5c19f22c1e7
Revises: d9705420e56f
Create Date: 2025-04-14 15:16:35.442786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e5c19f22c1e7'
down_revision: Union[str, None] = 'd9705420e56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('college_students', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.add_column('college_students', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    op.drop_constraint('college_students_ibfk_2', 'college_students', type_='foreignkey')
    op.create_foreign_key(None, 'college_students', 'users', ['uploaded_by'], ['user_id'])
    op.drop_column('college_students', 'created_at')
    op.drop_column('college_students', 'created_by')
    op.add_column('senior_high_students', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.add_column('senior_high_students', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    op.drop_constraint('senior_high_students_ibfk_2', 'senior_high_students', type_='foreignkey')
    op.create_foreign_key(None, 'senior_high_students', 'users', ['uploaded_by'], ['user_id'])
    op.drop_column('senior_high_students', 'created_at')
    op.drop_column('senior_high_students', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('senior_high_students', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('senior_high_students', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'senior_high_students', type_='foreignkey')
    op.create_foreign_key('senior_high_students_ibfk_2', 'senior_high_students', 'users', ['created_by'], ['user_id'])
    op.drop_column('senior_high_students', 'uploaded_at')
    op.drop_column('senior_high_students', 'uploaded_by')
    op.add_column('college_students', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('college_students', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'college_students', type_='foreignkey')
    op.create_foreign_key('college_students_ibfk_2', 'college_students', 'users', ['created_by'], ['user_id'])
    op.drop_column('college_students', 'uploaded_at')
    op.drop_column('college_students', 'uploaded_by')
    # ### end Alembic commands ###
