"""added tracking upload data for college and shs tables

Revision ID: e870875d730a
Revises: bc12cf77f49f
Create Date: 2025-04-13 22:07:23.905442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e870875d730a'
down_revision: Union[str, None] = 'bc12cf77f49f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
